spring:
  jpa:
    #database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect
    database-platform: it.plansoft.sql3.dialect.SQLiteDialect
    #hibernate.ddl-auto: update
    #hibernate.ddl-auto: none
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:sqlite:src/main/resources/publication.db
    driver-class-name: org.sqlite.JDBC
#    username: admin
#    password: admin