# configurazione del server
spring:
  profiles:
    active: sqlite
    #active: mysql
    #active: postgres

server:
  port: 8092
  servlet:
    contextPath: /publication


# impostazioni per hibernate
hibernate:
  hbm2ddl:
    auto: none
  show-sql: true